name: Package libgeos++-inline-dev
on:
  repository_dispatch:
    types:
    - package-master
  push:
    branches:
    - main
jobs:
  package:
    uses: jrl-umi3218/github-actions/.github/workflows/package-project.yml@master
    with:
      main-branch: main
      update-stable-and-head: true
      matrix: |
          {
            "dist": ["jammy"],
            "arch": ["amd64"]
          }
    secrets:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
